import type { QuranMediaTemplate } from './types';

export const QURAN_MEDIA_TEMPLATES: QuranMediaTemplate[] = [
  // 1. Minimal Quran
  {
    template_id: 'minimal_quran',
    nameAr: 'المصحف البسيط (Minimal Quran)',
    nameEn: 'Minimal Quran',
    descriptionAr: 'تصميم بسيط ومركّز على جلال الآيات بالرسم العثماني وخلفية داكنة خالية من المشتتات.',
    descriptionEn: 'Ultra-clean, distraction-free typographic layout focused on the majesty of the Uthmani Quranic text.',
    category: 'minimal',
    categoryNameAr: 'بسيط وهادئ',
    categoryNameEn: 'Minimalist',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.15,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#10b981',
      secondary: '#0f172a',
      accent: '#f59e0b',
      textArabic: '#ffffff',
      textTranslation: '#94a3b8',
      highlightKaraoke: '#34d399',
      backgroundGradient: ['#090d16', '#020617'],
      overlayColor: 'rgba(2, 6, 23, 0.6)',
      borderGlowColor: 'rgba(16, 185, 129, 0.2)',
    },
    animation: {
      cameraMotion: 'none',
      cameraIntensity: 0.04,
      particles: false,
      particleType: 'none',
      waveformVisualizer: false,
      waveformStyle: 'bars',
      calligraphyGlowPulse: false,
    },
    transitions: {
      sceneTransition: 'fade',
      transitionDuration: 0.8,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 60,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'none',
      recitationVolume: 1.0,
      ambientVolume: 0.0,
      sidechainDucking: false,
      duckAmountDb: 0,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4,
      includeIntro: false,
      introDuration: 0,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 2,
      outroAnimation: 'fade',
      stylePreset: 'minimal_pure',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #090d16 0%, #020617 100%)',
      tags: ['Clean', 'Pure Typo', 'No Distractions', 'Dark Mode'],
      badge: 'Popular',
      badgeColor: 'emerald',
    },
  },

  // 2. Cinematic Nature
  {
    template_id: 'cinematic_nature',
    nameAr: 'الطبيعة السينمائية (Cinematic Nature)',
    nameEn: 'Cinematic Nature',
    descriptionAr: 'مشاهد طبيعية ساحرة بحركة كاميرا سينمائية بطيئة وتدرجات خضراء مع مؤثرات صوتية بيئية.',
    descriptionEn: 'Majestic cinematic landscapes with slow Ken Burns motion, lush gradients, and serene atmospheric ambient sound.',
    category: 'nature',
    categoryNameAr: 'طبيعة سينمائية',
    categoryNameEn: 'Nature & Scenery',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '16:9',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Outfit',
      fontSizeScale: 1.05,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#059669',
      secondary: '#064e3b',
      accent: '#fbbf24',
      textArabic: '#fef3c7',
      textTranslation: '#f8fafc',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#064e3b', '#0f291e', '#020617'],
      overlayColor: 'rgba(6, 78, 59, 0.35)',
      borderGlowColor: 'rgba(251, 191, 36, 0.3)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.14,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.18,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 2.5,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 3.5,
      outroAnimation: 'slow_drift',
      stylePreset: 'cinematic_nature_4k',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(135deg, #064e3b 0%, #0f291e 50%, #020617 100%)',
      tags: ['4K Nature', 'Ken Burns', 'Ambient Sound', 'Cinematic'],
      badge: 'Featured',
      badgeColor: 'amber',
    },
  },

  // 3. Islamic Geometry
  {
    template_id: 'islamic_geometry',
    nameAr: 'الزخارف الإسلامية (Islamic Geometry)',
    nameEn: 'Islamic Geometry',
    descriptionAr: 'أنماط هندسية إسلامية متحركة وإطارات أرابيسك مذهبة تليق بقدسية القرآن الكريم.',
    descriptionEn: 'Mesmerizing sacred geometric arabesques with radiant golden latticework and traditional patterns.',
    category: 'islamic_art',
    categoryNameAr: 'الفن والزخرفة الإسلامية',
    categoryNameEn: 'Islamic Art & Geometry',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '1:1',
    fonts: {
      arabicFont: 'Traditional Arabic',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0.5,
    },
    colors: {
      primary: '#d97706',
      secondary: '#78350f',
      accent: '#fde047',
      textArabic: '#fef08a',
      textTranslation: '#ffffff',
      highlightKaraoke: '#eab308',
      backgroundGradient: ['#1c1917', '#292524', '#0c0a09'],
      overlayColor: 'rgba(28, 25, 23, 0.5)',
      borderGlowColor: 'rgba(234, 179, 8, 0.4)',
    },
    animation: {
      cameraMotion: 'zoom_in',
      cameraIntensity: 0.08,
      particles: true,
      particleType: 'geometric',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'dissolve',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 70,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'tarteel',
      ambientPreset: 'celestial_reverb',
      recitationVolume: 1.0,
      ambientVolume: 0.14,
      sidechainDucking: true,
      duckAmountDb: 16,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'fade',
      stylePreset: 'arabesque_gold',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'radial-gradient(circle at center, #78350f 0%, #1c1917 70%, #0c0a09 100%)',
      tags: ['Arabesque', 'Gold Latticework', 'Traditional', 'Square/Reels'],
    },
  },

  // 4. Arabic Calligraphy
  {
    template_id: 'arabic_calligraphy',
    nameAr: 'الخط العربي الأصيل (Arabic Calligraphy)',
    nameEn: 'Arabic Calligraphy',
    descriptionAr: 'إبراز جماليات الخط العربي ورسم المصحف مع إضاءة ذهبية للكلمات ونقاء بصري فائق.',
    descriptionEn: 'High-contrast aesthetic celebrating authentic calligraphy with gleaming golden highlights.',
    category: 'islamic_art',
    categoryNameAr: 'الفن والزخرفة الإسلامية',
    categoryNameEn: 'Islamic Art & Geometry',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Scheherazade New',
      translationFont: 'Inter',
      fontSizeScale: 1.25,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#eab308',
      secondary: '#451a03',
      accent: '#fef08a',
      textArabic: '#fffbeb',
      textTranslation: '#cbd5e1',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#1e1b4b', '#0f172a', '#020617'],
      overlayColor: 'rgba(15, 23, 42, 0.4)',
      borderGlowColor: 'rgba(234, 179, 8, 0.35)',
    },
    animation: {
      cameraMotion: 'pan_up',
      cameraIntensity: 0.1,
      particles: true,
      particleType: 'dust',
      waveformVisualizer: true,
      waveformStyle: 'line',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 75,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.15,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'calligraphy_master',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #1e1b4b 0%, #0f172a 60%, #020617 100%)',
      tags: ['Scheherazade', 'Golden Calligraphy', 'High Contrast'],
    },
  },

  // 5. Night Reflection
  {
    template_id: 'night_reflection',
    nameAr: 'سكينة الليل (Night Reflection)',
    nameEn: 'Night Reflection',
    descriptionAr: 'أجواء ليلية هادئة وسماء صافية تناسب تلاوات قيام الليل والتدبر الخاشع.',
    descriptionEn: 'Deep nocturnal blue hues and serene moonlit atmosphere designed for night prayers and deep reflection.',
    category: 'celestial',
    categoryNameAr: 'فلكي وكوني',
    categoryNameEn: 'Celestial & Skies',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#38bdf8',
      secondary: '#0c4a6e',
      accent: '#7dd3fc',
      textArabic: '#e0f2fe',
      textTranslation: '#94a3b8',
      highlightKaraoke: '#38bdf8',
      backgroundGradient: ['#082f49', '#0f172a', '#020617'],
      overlayColor: 'rgba(8, 47, 73, 0.4)',
      borderGlowColor: 'rgba(56, 189, 248, 0.3)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.1,
      particles: true,
      particleType: 'stars',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'dissolve',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'night_desert',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'fade',
      stylePreset: 'nocturnal_serenity',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #082f49 0%, #0f172a 60%, #020617 100%)',
      tags: ['Nocturnal', 'Deep Blue', 'Qiyam', 'Tranquil'],
    },
  },

  // 6. Sunrise
  {
    template_id: 'sunrise',
    nameAr: 'شروق الأمل (Sunrise)',
    nameEn: 'Sunrise Glow',
    descriptionAr: 'أشعة فجر ذهبية دافئة وألوان وردية ملهمة لآيات الأمل وبشائر الصابرين وسورة الضحى.',
    descriptionEn: 'Golden dawn illumination and pastel amber skies inspiring spiritual hope and new beginnings.',
    category: 'celestial',
    categoryNameAr: 'فلكي وكوني',
    categoryNameEn: 'Celestial & Skies',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Outfit',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#f59e0b',
      secondary: '#7c2d12',
      accent: '#fbbf24',
      textArabic: '#fffbeb',
      textTranslation: '#fed7aa',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#7c2d12', '#451a03', '#0f172a'],
      overlayColor: 'rgba(124, 45, 18, 0.35)',
      borderGlowColor: 'rgba(251, 191, 36, 0.4)',
    },
    animation: {
      cameraMotion: 'pan_up',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.15,
      sidechainDucking: true,
      duckAmountDb: 16,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'golden_dawn',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(160deg, #7c2d12 0%, #451a03 50%, #0f172a 100%)',
      tags: ['Dawn', 'Golden Hope', 'Ad-Duha', 'Warm Pastel'],
    },
  },

  // 7. Ocean
  {
    template_id: 'ocean',
    nameAr: 'أعماق البحار (Ocean)',
    nameEn: 'Ocean Depths',
    descriptionAr: 'أمواج محيطية هادئة وأعماق فيروزية تذكر بعظمة خلق البحار وقصة يونس وسفينة نوح.',
    descriptionEn: 'Deep oceanic turquoise waters and serene waves reflecting the immense power and mercy of Allah.',
    category: 'nature',
    categoryNameAr: 'طبيعة سينمائية',
    categoryNameEn: 'Nature & Scenery',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '16:9',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#06b6d4',
      secondary: '#164e63',
      accent: '#67e8f9',
      textArabic: '#ecfeff',
      textTranslation: '#cffafe',
      highlightKaraoke: '#22d3ee',
      backgroundGradient: ['#164e63', '#083344', '#020617'],
      overlayColor: 'rgba(22, 78, 99, 0.4)',
      borderGlowColor: 'rgba(34, 211, 238, 0.3)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'dust',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'ocean_tranquility',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #164e63 0%, #083344 60%, #020617 100%)',
      tags: ['Ocean', 'Turquoise', 'Jonah', 'Seas'],
    },
  },

  // 8. Mountains
  {
    template_id: 'mountains',
    nameAr: 'شموخ الجبال (Mountains)',
    nameEn: 'Majestic Mountains',
    descriptionAr: 'قمم جبلية شامخة وتضاريس مهيبة تجسد قوله تعالى: {وَٱلْجِبَالَ أَوْتَادًۭا}.',
    descriptionEn: 'Towering alpine summits and dramatic mountain ridges illustrating the firm geological pegs of earth.',
    category: 'nature',
    categoryNameAr: 'طبيعة سينمائية',
    categoryNameEn: 'Nature & Scenery',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '16:9',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#64748b',
      secondary: '#1e293b',
      accent: '#f8fafc',
      textArabic: '#f1f5f9',
      textTranslation: '#cbd5e1',
      highlightKaraoke: '#38bdf8',
      backgroundGradient: ['#1e293b', '#0f172a', '#020617'],
      overlayColor: 'rgba(30, 41, 59, 0.45)',
      borderGlowColor: 'rgba(248, 250, 252, 0.2)',
    },
    animation: {
      cameraMotion: 'pan_left',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'dust',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.15,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'alpine_grandeur',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #1e293b 0%, #0f172a 60%, #020617 100%)',
      tags: ['Mountains', 'Rock & Snow', 'Epic', '16:9 Landscape'],
    },
  },

  // 9. Desert
  {
    template_id: 'desert',
    nameAr: 'رمال الصحراء (Desert)',
    nameEn: 'Desert Dunes',
    descriptionAr: 'كثبان رملية ممتدة وسكون صحراوي عريق يعكس بيئة الجزيرة والقصص النبوية.',
    descriptionEn: 'Vast golden sand dunes and timeless desert horizons evoking prophetic journeys and stillness.',
    category: 'nature',
    categoryNameAr: 'طبيعة سينمائية',
    categoryNameEn: 'Nature & Scenery',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#d97706',
      secondary: '#78350f',
      accent: '#fef08a',
      textArabic: '#fffbeb',
      textTranslation: '#fed7aa',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#78350f', '#451a03', '#0f172a'],
      overlayColor: 'rgba(120, 53, 15, 0.4)',
      borderGlowColor: 'rgba(245, 158, 11, 0.35)',
    },
    animation: {
      cameraMotion: 'pan_right',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'dust',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'night_desert',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'golden_dunes',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #78350f 0%, #451a03 50%, #0f172a 100%)',
      tags: ['Desert', 'Dunes', 'Warm Amber', 'Prophetic Path'],
    },
  },

  // 10. Rain
  {
    template_id: 'rain',
    nameAr: 'غيث الرحمة (Rain)',
    nameEn: 'Gentle Rain',
    descriptionAr: 'قطرات مطر مباركة وسحب ماطرة مع صوت خرير الماء وآيات إحياء الأرض بعد موتها.',
    descriptionEn: 'Soothing rain precipitation, misty skies, and gentle water soundscapes bringing dead earth to life.',
    category: 'nature',
    categoryNameAr: 'طبيعة سينمائية',
    categoryNameEn: 'Nature & Scenery',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#0ea5e9',
      secondary: '#0369a1',
      accent: '#bae6fd',
      textArabic: '#f0f9ff',
      textTranslation: '#e0f2fe',
      highlightKaraoke: '#38bdf8',
      backgroundGradient: ['#0369a1', '#075985', '#0f172a'],
      overlayColor: 'rgba(3, 105, 161, 0.4)',
      borderGlowColor: 'rgba(56, 189, 248, 0.3)',
    },
    animation: {
      cameraMotion: 'zoom_in',
      cameraIntensity: 0.1,
      particles: true,
      particleType: 'rain',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'dissolve',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'rain_gentle',
      recitationVolume: 1.0,
      ambientVolume: 0.18,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'gentle_rainfall',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #0369a1 0%, #075985 50%, #0f172a 100%)',
      tags: ['Rain', 'Water Drops', 'Revival', 'Gentle Mist'],
    },
  },

  // 11. Stars
  {
    template_id: 'stars',
    nameAr: 'مواقع النجوم (Stars)',
    nameEn: 'Cosmic Stars',
    descriptionAr: 'سدم كونية وجزيئات ضوئية متلألئة تتناغم مع القسم الإلهي: {فَلَآ أُقْسِمُ بِمَوَٰقِعِ ٱلنُّجُومِ}.',
    descriptionEn: 'Deep space nebulae and sparkling celestial starfields contemplating cosmic oaths and immense creation.',
    category: 'celestial',
    categoryNameAr: 'فلكي وكوني',
    categoryNameEn: 'Celestial & Skies',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.15,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#8b5cf6',
      secondary: '#4c1d95',
      accent: '#c4b5fd',
      textArabic: '#faf5ff',
      textTranslation: '#e9d5ff',
      highlightKaraoke: '#a855f7',
      backgroundGradient: ['#4c1d95', '#2e1065', '#020617'],
      overlayColor: 'rgba(76, 29, 149, 0.4)',
      borderGlowColor: 'rgba(168, 85, 247, 0.35)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'stars',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'celestial_reverb',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'deep_space_nebula',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'radial-gradient(circle at center, #4c1d95 0%, #2e1065 50%, #020617 100%)',
      tags: ['Cosmos', 'Nebula', 'Stars', 'Space'],
      badge: 'Popular',
      badgeColor: 'purple',
    },
  },

  // 12. Mosque Architecture
  {
    template_id: 'mosque_architecture',
    nameAr: 'العمارة والمحاريب (Mosque Architecture)',
    nameEn: 'Mosque Architecture',
    descriptionAr: 'أقواس وقباب إسلامية مهيبة مع أشعة شمس تخترق المحاريب بأجواء روحانية خالصة.',
    descriptionEn: 'Majestic grand domes, soaring minarets, and divine sunlight streaming through sanctuary arches.',
    category: 'islamic_art',
    categoryNameAr: 'الفن والزخرفة الإسلامية',
    categoryNameEn: 'Islamic Art & Geometry',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '16:9',
    fonts: {
      arabicFont: 'Traditional Arabic',
      translationFont: 'Outfit',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#14b8a6',
      secondary: '#134e4a',
      accent: '#fde047',
      textArabic: '#f0fdfa',
      textTranslation: '#ccfbf1',
      highlightKaraoke: '#2dd4bf',
      backgroundGradient: ['#134e4a', '#042f2e', '#020617'],
      overlayColor: 'rgba(19, 78, 74, 0.4)',
      borderGlowColor: 'rgba(253, 224, 71, 0.3)',
    },
    animation: {
      cameraMotion: 'zoom_out',
      cameraIntensity: 0.1,
      particles: true,
      particleType: 'dust',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 80,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'celestial_reverb',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'sanctuary_arches',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #134e4a 0%, #042f2e 50%, #020617 100%)',
      tags: ['Mosque', 'Grand Domes', 'Arches', 'Sanctuary'],
    },
  },

  // 13. Abstract Light
  {
    template_id: 'abstract_light',
    nameAr: 'النور التجريدي (Abstract Light)',
    nameEn: 'Abstract Light',
    descriptionAr: 'تدرجات ضوئية تجريدية وأمواج أثيرية تعبر عن النور والسكينة دون تجسيد.',
    descriptionEn: 'Ethereal glowing light rays and abstract luminous flow conveying Divine light and serenity.',
    category: 'minimal',
    categoryNameAr: 'بسيط وهادئ',
    categoryNameEn: 'Minimalist',
    supported_aspect_ratios: ['9:16', '16:9', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.15,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#6366f1',
      secondary: '#312e81',
      accent: '#a5b4fc',
      textArabic: '#eef2ff',
      textTranslation: '#c7d2fe',
      highlightKaraoke: '#818cf8',
      backgroundGradient: ['#312e81', '#1e1b4b', '#020617'],
      overlayColor: 'rgba(49, 46, 129, 0.4)',
      borderGlowColor: 'rgba(129, 140, 248, 0.35)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.1,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'dissolve',
      transitionDuration: 1.0,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 75,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.15,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4.5,
      includeIntro: true,
      introDuration: 2,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 3,
      outroAnimation: 'slow_drift',
      stylePreset: 'luminous_flow',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'radial-gradient(circle at top right, #312e81 0%, #1e1b4b 50%, #020617 100%)',
      tags: ['Light Rays', 'Abstract', 'Spiritual Glow', 'Ethereal'],
    },
  },

  // 14. Short Reminder
  {
    template_id: 'short_reminder',
    nameAr: 'تذكرة سريعة (Short Reminder)',
    nameEn: 'Short Reminder',
    descriptionAr: 'قالب سريع ومكثف للآيات القصيرة مع تمييز سريع للكلمات وبطاقة ختامية تدعو للتدبر والمشاركة.',
    descriptionEn: 'Punchy, high-impact short-form layout designed for powerful one-verse spiritual reminders.',
    category: 'social_media',
    categoryNameAr: 'شبكات التواصل والفيديو القصير',
    categoryNameEn: 'Shorts & Social Reels',
    supported_aspect_ratios: ['9:16', '1:1', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.25,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#f59e0b',
      secondary: '#0f172a',
      accent: '#fbbf24',
      textArabic: '#ffffff',
      textTranslation: '#cbd5e1',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#0f172a', '#020617'],
      overlayColor: 'rgba(2, 6, 23, 0.65)',
      borderGlowColor: 'rgba(245, 158, 11, 0.4)',
    },
    animation: {
      cameraMotion: 'zoom_in',
      cameraIntensity: 0.08,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 0.6,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 90,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.12,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 3.5,
      includeIntro: false,
      introDuration: 0,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 2.5,
      outroAnimation: 'slide_up',
      stylePreset: 'fast_reminder_card',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #1e293b 0%, #0f172a 50%, #020617 100%)',
      tags: ['Snackable', 'High Impact', '1 Verse', 'Fast'],
    },
  },

  // 15. Instagram Reel
  {
    template_id: 'instagram_reel',
    nameAr: 'إنستغرام ريلز (Instagram Reel)',
    nameEn: 'Instagram Reel',
    descriptionAr: 'مُحسّن بنسبة 9:16 مع مراعاة مناطق واجهة إنستغرام الآمنة وخطوط عصرية وتمييز للكلمات.',
    descriptionEn: 'Engineered specifically for Instagram Reels (9:16) with safe-zone margin offsets and high-retention visuals.',
    category: 'social_media',
    categoryNameAr: 'شبكات التواصل والفيديو القصير',
    categoryNameEn: 'Shorts & Social Reels',
    supported_aspect_ratios: ['9:16', '4:5'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Outfit',
      fontSizeScale: 1.2,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#ec4899',
      secondary: '#831843',
      accent: '#f472b6',
      textArabic: '#fdf2f8',
      textTranslation: '#ffffff',
      highlightKaraoke: '#fbbf24',
      backgroundGradient: ['#831843', '#1e1b4b', '#020617'],
      overlayColor: 'rgba(131, 24, 67, 0.35)',
      borderGlowColor: 'rgba(244, 114, 182, 0.35)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.14,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 0.8,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 120, // Avoid IG bottom caption & right action icons
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4,
      includeIntro: true,
      introDuration: 1.5,
      introAnimation: 'slide_up',
      includeOutro: true,
      outroDuration: 2.5,
      outroAnimation: 'fade',
      stylePreset: 'ig_reels_pro',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(160deg, #831843 0%, #1e1b4b 50%, #020617 100%)',
      tags: ['Instagram 9:16', 'Safe Margin 120px', 'Viral Hook', 'Reels'],
      badge: '9:16 Optimized',
      badgeColor: 'pink',
    },
  },

  // 16. TikTok
  {
    template_id: 'tiktok',
    nameAr: 'تيك توك فائق الحركية (TikTok Dynamic)',
    nameEn: 'TikTok Dynamic',
    descriptionAr: 'قالب 9:16 تفاعلي مع إيقاع سريع، تمييز كلمات بوهج ذهبي، ومخطط صوتي واضح.',
    descriptionEn: 'High-engagement 9:16 format with rapid word karaoke highlight, dynamic audio visualizer, and optimal safe zones.',
    category: 'social_media',
    categoryNameAr: 'شبكات التواصل والفيديو القصير',
    categoryNameEn: 'Shorts & Social Reels',
    supported_aspect_ratios: ['9:16'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.25,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#06b6d4',
      secondary: '#0f172a',
      accent: '#22d3ee',
      textArabic: '#ffffff',
      textTranslation: '#f8fafc',
      highlightKaraoke: '#00f2fe',
      backgroundGradient: ['#0f172a', '#083344', '#020617'],
      overlayColor: 'rgba(8, 51, 68, 0.45)',
      borderGlowColor: 'rgba(34, 211, 238, 0.4)',
    },
    animation: {
      cameraMotion: 'zoom_in',
      cameraIntensity: 0.15,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'wipeleft',
      transitionDuration: 0.7,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 130, // Avoid TikTok right buttons and bottom text
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.15,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 3.5,
      includeIntro: false,
      introDuration: 0,
      introAnimation: 'fade',
      includeOutro: true,
      outroDuration: 2,
      outroAnimation: 'slide_up',
      stylePreset: 'tiktok_viral_sub',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(180deg, #0f172a 0%, #083344 50%, #020617 100%)',
      tags: ['TikTok', 'Safe Margin 130px', 'Neon Cyan Glow', 'Rapid'],
    },
  },

  // 17. YouTube Shorts
  {
    template_id: 'youtube_shorts',
    nameAr: 'يوتيوب شورتس (YouTube Shorts)',
    nameEn: 'YouTube Shorts',
    descriptionAr: 'قالب رأسي 9:16 مع خطوط واضحة وترجمة ثنائية متناسقة ومقدمة أنيقة.',
    descriptionEn: 'Vertical 9:16 template calibrated for YouTube Shorts retention with clean typography and subtle ambient mixing.',
    category: 'social_media',
    categoryNameAr: 'شبكات التواصل والفيديو القصير',
    categoryNameEn: 'Shorts & Social Reels',
    supported_aspect_ratios: ['9:16'],
    recommendedAspectRatio: '9:16',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Roboto',
      fontSizeScale: 1.2,
      arabicFontWeight: 'bold',
      letterSpacing: 0,
    },
    colors: {
      primary: '#ef4444',
      secondary: '#7f1d1d',
      accent: '#fca5a5',
      textArabic: '#ffffff',
      textTranslation: '#f1f5f9',
      highlightKaraoke: '#fbbf24',
      backgroundGradient: ['#7f1d1d', '#1e1b4b', '#020617'],
      overlayColor: 'rgba(127, 29, 29, 0.35)',
      borderGlowColor: 'rgba(239, 68, 68, 0.35)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.12,
      particles: true,
      particleType: 'stars',
      waveformVisualizer: true,
      waveformStyle: 'bars',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 0.8,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 100,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.16,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 4,
      includeIntro: true,
      introDuration: 1.5,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 2.5,
      outroAnimation: 'fade',
      stylePreset: 'yt_shorts_master',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(160deg, #7f1d1d 0%, #1e1b4b 50%, #020617 100%)',
      tags: ['YT Shorts', '9:16', 'Calligraphy', 'High Engagement'],
    },
  },

  // 18. YouTube Landscape
  {
    template_id: 'youtube_landscape',
    nameAr: 'يوتيوب الأفقي العريض (YouTube Landscape 16:9)',
    nameEn: 'YouTube Landscape 16:9',
    descriptionAr: 'إنتاج سينمائي أفقي عريض 16:9 بدقة 4K مع ترجمة مصحف احترافية، وهوامش آمنة للشاشات الكبيرة والتلفاز.',
    descriptionEn: 'Full 16:9 widescreen 4K broadcasting template with cinematic camera motion, expansive typography, and TV safe zones.',
    category: 'broadcast',
    categoryNameAr: 'البث والشاشات العريضة (16:9)',
    categoryNameEn: 'Broadcast & TV (16:9)',
    supported_aspect_ratios: ['16:9'],
    recommendedAspectRatio: '16:9',
    fonts: {
      arabicFont: 'Amiri Quran',
      translationFont: 'Inter',
      fontSizeScale: 1.1,
      arabicFontWeight: 'bold',
      letterSpacing: 0.5,
    },
    colors: {
      primary: '#10b981',
      secondary: '#064e3b',
      accent: '#fbbf24',
      textArabic: '#fef3c7',
      textTranslation: '#f8fafc',
      highlightKaraoke: '#f59e0b',
      backgroundGradient: ['#064e3b', '#0f172a', '#020617'],
      overlayColor: 'rgba(2, 6, 23, 0.45)',
      borderGlowColor: 'rgba(245, 158, 11, 0.35)',
    },
    animation: {
      cameraMotion: 'ken_burns',
      cameraIntensity: 0.14,
      particles: true,
      particleType: 'light_orbs',
      waveformVisualizer: true,
      waveformStyle: 'wave',
      calligraphyGlowPulse: true,
    },
    transitions: {
      sceneTransition: 'crossfade',
      transitionDuration: 1.2,
    },
    text_positions: {
      arabicVerticalPosition: 'middle',
      translationVerticalPosition: 'bottom',
      safeZoneMarginPx: 60,
      alignment: 'center',
      dualLanguageStacked: true,
      wordHighlightActive: true,
    },
    audio_behavior: {
      reciterStyle: 'murattal',
      ambientPreset: 'deep_serenity',
      recitationVolume: 1.0,
      ambientVolume: 0.18,
      sidechainDucking: true,
      duckAmountDb: 18,
      audioNormalize: true,
    },
    scene_structure: {
      defaultSceneDuration: 5,
      includeIntro: true,
      introDuration: 3,
      introAnimation: 'zoom_reveal',
      includeOutro: true,
      outroDuration: 4,
      outroAnimation: 'slow_drift',
      stylePreset: 'cinema_broadcast_4k',
    },
    preview: {
      previewImageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
      backdropCss: 'linear-gradient(135deg, #064e3b 0%, #0f172a 50%, #020617 100%)',
      tags: ['16:9 Widescreen', '4K TV Ready', 'Broadcast', 'Full Recitations'],
      badge: '16:9 Broadcast',
      badgeColor: 'emerald',
    },
  },
];
