import { CANONICAL_SURAHS, type CanonicalSurahMeta } from '@quran-media/quran';

export interface SurahExtendedMeta extends CanonicalSurahMeta {
  meaningEn: string;
  revelationOrder: number;
  shortDescAr: string;
  shortDescEn: string;
  featuredMedia: {
    videos: number;
    stories: number;
    images: number;
  };
}

// Translations and descriptions for the complete 114 Surahs
const SURAH_DESCRIPTIONS: Record<
  number,
  {
    meaningEn: string;
    revelationOrder: number;
    shortDescAr: string;
    shortDescEn: string;
    videos: number;
    stories: number;
    images: number;
  }
> = {
  1: {
    meaningEn: 'The Opener',
    revelationOrder: 5,
    shortDescAr: 'أم الكتاب والسبع المثاني، تشتمل على مجمل أصول الدين والتوحيد والعبادة والرجاء.',
    shortDescEn: 'The Opening of the Quran, establishing the core foundations of monotheism, praise, and prayer.',
    videos: 42,
    stories: 18,
    images: 64,
  },
  2: {
    meaningEn: 'The Cow',
    revelationOrder: 87,
    shortDescAr: 'أطول سور القرآن، تتضمن أحكام الشريعة وآية الكرسي وقصة الاستخلاف وبني إسرائيل.',
    shortDescEn: 'The longest chapter in the Quran, containing Ayat Al-Kursi, comprehensive legislation, and prophetic covenants.',
    videos: 128,
    stories: 56,
    images: 190,
  },
  3: {
    meaningEn: 'Family of Imran',
    revelationOrder: 89,
    shortDescAr: 'تثبيت العقيدة ودلائل النبوة وقصة مريم وعيسى عليهما السلام وغزوة أحد واليقين.',
    shortDescEn: 'Affirming pure monotheism, the virgin birth of Jesus, and resilience during adversity.',
    videos: 64,
    stories: 28,
    images: 85,
  },
  4: {
    meaningEn: 'The Women',
    revelationOrder: 92,
    shortDescAr: 'تنظيم الحقوق الأسرية والعدالة الاجتماعية وحفظ أموال اليتامى والميراث والقسط.',
    shortDescEn: 'Focusing on justice, the rights of orphans and women, family law, and upright social conduct.',
    videos: 36,
    stories: 14,
    images: 48,
  },
  5: {
    meaningEn: 'The Table Spread',
    revelationOrder: 112,
    shortDescAr: 'الوفاء بالعقود والعهود، وبيان الحلال والحرام، وكمال الدين وتمام النعمة.',
    shortDescEn: 'Emphasizing the fulfillment of covenants, dietary guidelines, and the perfection of religion.',
    videos: 32,
    stories: 12,
    images: 40,
  },
  6: {
    meaningEn: 'The Cattle',
    revelationOrder: 55,
    shortDescAr: 'دلائل التوحيد الكونية، ومحاجة المشركين، وتفصيل آيات الله في الآفاق والأنفس.',
    shortDescEn: 'Cosmic signs of divine unity, refutation of polytheism, and contemplating creation.',
    videos: 28,
    stories: 10,
    images: 35,
  },
  7: {
    meaningEn: 'The Heights',
    revelationOrder: 39,
    shortDescAr: 'الصراع بين الحق والباطل، وقصص الأنبياء مع أقوامهم وأصحاب الأعراف ومصير الأمم.',
    shortDescEn: 'The eternal struggle between truth and falsehood, recounting prophetic missions and the Day of Sorting.',
    videos: 30,
    stories: 15,
    images: 42,
  },
  8: {
    meaningEn: 'The Spoils of War',
    revelationOrder: 88,
    shortDescAr: 'دروس غزوة بدر الكبرى، وسنن النصر والهزيمة، وأهمية التقوى والتوكل على الله.',
    shortDescEn: 'The spiritual lessons of the Battle of Badr, divine assistance, and steadfast reliance upon Allah.',
    videos: 18,
    stories: 8,
    images: 24,
  },
  9: {
    meaningEn: 'The Repentance',
    revelationOrder: 113,
    shortDescAr: 'البراءة من العهود الناكثة، وفضل التوبة الصادقة وتطهير النفوس ومواقف غزوة تبوك.',
    shortDescEn: 'Disavowal of hypocritical covenants, sincere repentance, and unwavering dedication.',
    videos: 22,
    stories: 9,
    images: 30,
  },
  10: {
    meaningEn: 'Jonah',
    revelationOrder: 51,
    shortDescAr: 'براهين الوحي والقرآن المعجز، وقصص نوح وموسى ويونس وتفريج الكروب بالإيمان.',
    shortDescEn: 'Divine signs of revelation, wisdom in destiny, and the salvation of Jonah’s people.',
    videos: 25,
    stories: 11,
    images: 32,
  },
  11: {
    meaningEn: 'Hud',
    revelationOrder: 52,
    shortDescAr: 'ثبات الأنبياء في مواجهة الطغيان، وقصة نوح وسفينته، وهود وصالح وشعيب ولوط.',
    shortDescEn: 'Steadfastness against oppression, the Ark of Noah, and the historical destiny of ancient nations.',
    videos: 40,
    stories: 22,
    images: 55,
  },
  12: {
    meaningEn: 'Joseph',
    revelationOrder: 53,
    shortDescAr: 'أحسن القصص، رحلة يوسف عليه السلام من غيابات الجب والسجن إلى عرش العزة والتمكين.',
    shortDescEn: 'The Best of Stories, chronicling Prophet Joseph’s journey from the well to noble elevation.',
    videos: 95,
    stories: 48,
    images: 120,
  },
  13: {
    meaningEn: 'The Thunder',
    revelationOrder: 96,
    shortDescAr: 'تسبيح الرعد والملائكة بحمد الله، وحقيقة الإيمان وقوة الحق وسقوط الباطل كالزبد.',
    shortDescEn: 'The cosmic thunder glorifying Allah, tranquil hearts finding peace in remembrance.',
    videos: 35,
    stories: 16,
    images: 45,
  },
  14: {
    meaningEn: 'Abraham',
    revelationOrder: 72,
    shortDescAr: 'دعوة إبراهيم عليه السلام، ونعم الله على العباد، ومثل الكلمة الطيبة كشجرة طيبة.',
    shortDescEn: 'The prayers of Abraham, gratitude for divine favors, and the parable of the good word.',
    videos: 38,
    stories: 19,
    images: 50,
  },
  15: {
    meaningEn: 'The Rocky Tract',
    revelationOrder: 54,
    shortDescAr: 'حفظ الله للذكر الحكيم، ومواقف التكذيب، وسعة رحمة الله بالمؤمنين وتسليتهم.',
    shortDescEn: 'Divine preservation of the Quran, patience during mockery, and angelic glad tidings.',
    videos: 20,
    stories: 8,
    images: 28,
  },
  16: {
    meaningEn: 'The Bee',
    revelationOrder: 70,
    shortDescAr: 'سورة النعم الكبرى، تتناول عجائب خلق النحل وعسل الشفاء والإنعام الإلهي الشامل.',
    shortDescEn: 'The Chapter of Blessings, highlighting the marvel of bees, natural healing, and justice.',
    videos: 32,
    stories: 14,
    images: 44,
  },
  17: {
    meaningEn: 'The Night Journey',
    revelationOrder: 50,
    shortDescAr: 'معجزة الإسراء والمعراج، ومكارم الأخلاق، وبر الوالدين، وجلال القرآن الكريم.',
    shortDescEn: 'The Miraculous Night Journey, filial piety towards parents, and the sublime power of the Quran.',
    videos: 52,
    stories: 26,
    images: 70,
  },
  18: {
    meaningEn: 'The Cave',
    revelationOrder: 69,
    shortDescAr: 'سورة الكهف ونور الجمعة، قصص الفتية، وصاحب الجنتين، وموسى والخضر، وذي القرنين.',
    shortDescEn: 'The sanctuary of Friday illumination, narrating the Sleepers of the Cave, Moses and Khidr, and Dhul-Qarnayn.',
    videos: 110,
    stories: 62,
    images: 160,
  },
  19: {
    meaningEn: 'Mary',
    revelationOrder: 44,
    shortDescAr: 'رحمة الله بزكريا ويحيى، وميلاد عيسى ابن مريم، ودعوة إبراهيم وإسماعيل وإدريس.',
    shortDescEn: 'The tender mercy bestowed upon Zechariah, Mary’s miraculous conception, and pure prophetic lineage.',
    videos: 68,
    stories: 34,
    images: 90,
  },
  20: {
    meaningEn: 'Ta-Ha',
    revelationOrder: 45,
    shortDescAr: 'مناجاة موسى في الوادي المقدس، وسحر فرعون، والقرآن شفاء لا يشقى من اتبعه.',
    shortDescEn: 'Divine discourse with Moses at Mount Sinai, the triumph of faith over sorcery, and tranquility.',
    videos: 55,
    stories: 27,
    images: 75,
  },
  21: {
    meaningEn: 'The Prophets',
    revelationOrder: 73,
    shortDescAr: 'نداءات الأنبياء واستجابة الدعاء (إبراهيم، أيوب، يونس، زكريا) والكون المفتوق.',
    shortDescEn: 'Heartfelt invocations of the prophets in their deepest distress, and cosmological origins.',
    videos: 60,
    stories: 31,
    images: 82,
  },
  22: {
    meaningEn: 'The Pilgrimage',
    revelationOrder: 103,
    shortDescAr: 'شعائر الحج العظيمة، ومناسك إبراهيم، وتعظيم حرمات الله وتقوى القلوب.',
    shortDescEn: 'The sacred rites of Hajj, the antiquity of the Kaaba, and the reverence of the heart.',
    videos: 26,
    stories: 10,
    images: 36,
  },
  23: {
    meaningEn: 'The Believers',
    revelationOrder: 74,
    shortDescAr: 'صفات الفالحين وخشوع الصلاة، ومراحل خلق الإنسان في الرحم، ونعيم الفردوس.',
    shortDescEn: 'The spiritual traits of the victorious believers, prayerful humility, and human embryology.',
    videos: 44,
    stories: 20,
    images: 60,
  },
  24: {
    meaningEn: 'The Light',
    revelationOrder: 102,
    shortDescAr: 'مثل نور الله الأعظم، وآداب الاستئذان، وحفظ العفة والطهارة وبراءة الصديقة عائشة.',
    shortDescEn: 'The Parable of Divine Light, social modesty, household sanctity, and spiritual illumination.',
    videos: 72,
    stories: 38,
    images: 105,
  },
  25: {
    meaningEn: 'The Criterion',
    revelationOrder: 42,
    shortDescAr: 'بركات القرآن والفرقان، وصفات عباد الرحمن الذين يمشون على الأرض هوناً.',
    shortDescEn: 'The Quran as the ultimate criterion between light and darkness, and traits of the Servants of the Merciful.',
    videos: 46,
    stories: 21,
    images: 65,
  },
  26: {
    meaningEn: 'The Poets',
    revelationOrder: 47,
    shortDescAr: 'عاقبة المكذبين، ومواقف موسى وإبراهيم ونوح وهود وصالح ولوط وشعيب مع أقوامهم.',
    shortDescEn: 'The eloquence of prophetic truth against empty rhetoric, vindicating the righteous.',
    videos: 24,
    stories: 9,
    images: 32,
  },
  27: {
    meaningEn: 'The Ants',
    revelationOrder: 48,
    shortDescAr: 'سليمان والجنود والنملة والهدهد، وإسلام ملكة سبأ، وعظمة التوحيد والقدرة.',
    shortDescEn: 'Solomon understanding the language of birds and ants, the submission of the Queen of Sheba.',
    videos: 36,
    stories: 18,
    images: 50,
  },
  28: {
    meaningEn: 'The Stories',
    revelationOrder: 49,
    shortDescAr: 'نشأة موسى في قصر فرعون، وموقف مدين، وبطش قارون وخسف داره بكنوزه.',
    shortDescEn: 'The infant Moses in the Nile, finding shelter in Midian, and the arrogance and fall of Korah.',
    videos: 38,
    stories: 19,
    images: 52,
  },
  29: {
    meaningEn: 'The Spider',
    revelationOrder: 85,
    shortDescAr: 'الابتلاء سنة ماضية في المؤمنين، ومثل من اتخذ من دون الله أولياء كبيت العنكبوت الواهي.',
    shortDescEn: 'Trials testing genuine conviction, and the fragility of idolizing anything besides Allah.',
    videos: 28,
    stories: 12,
    images: 38,
  },
  30: {
    meaningEn: 'The Romans',
    revelationOrder: 84,
    shortDescAr: 'نبوءة غلبة الروم، والآيات الكونية في خلق الأزواج والمودة والسماوات والأرض والرياح.',
    shortDescEn: 'The historical prophecy of Roman victory, marital serenity, and diverse tongues.',
    videos: 34,
    stories: 15,
    images: 46,
  },
  31: {
    meaningEn: 'Luqman',
    revelationOrder: 57,
    shortDescAr: 'وصايا لقمان الحكيم لابنه في التوحيد وبر الوالدين وإقامة الصلاة ومكارم الأخلاق.',
    shortDescEn: 'The timeless wisdom of Luqman to his son regarding humility, prayer, and character.',
    videos: 40,
    stories: 20,
    images: 54,
  },
  32: {
    meaningEn: 'The Prostration',
    revelationOrder: 75,
    shortDescAr: 'عظمة التنزيل، وسجود الخاشعين في الأسحار، وحقائق البعث والجزاء.',
    shortDescEn: 'The majesty of revelation, nocturnal devotions of the righteous, and resurrection.',
    videos: 22,
    stories: 8,
    images: 30,
  },
  33: {
    meaningEn: 'The Combined Forces',
    revelationOrder: 90,
    shortDescAr: 'غزوة الخندق وتكالب الأحزاب، ومقام النبي صلى الله عليه وسلم، وأمهات المؤمنين.',
    shortDescEn: 'The siege of Medina during the Battle of the Trench, and following the supreme prophetic model.',
    videos: 30,
    stories: 14,
    images: 42,
  },
  34: {
    meaningEn: 'Sheba',
    revelationOrder: 58,
    shortDescAr: 'تسبيح الجبال مع داود، وسيل العرم، وزوال حضارة سبأ حين كفروا بأنعم الله.',
    shortDescEn: 'The mountains echoing with David, Solomon’s jinns, and the flood of Arim dismantling Sheba.',
    videos: 20,
    stories: 9,
    images: 28,
  },
  35: {
    meaningEn: 'The Originator',
    revelationOrder: 43,
    shortDescAr: 'أجنحة الملائكة، وتدبير الأرزاق، وعظمة الخالق الذي لا يمسكه أحد إلا برحمته.',
    shortDescEn: 'The Angelic messengers with winged splendor, continuous sustenance, and divine majesty.',
    videos: 22,
    stories: 10,
    images: 30,
  },
  36: {
    meaningEn: 'Ya-Sin',
    revelationOrder: 41,
    shortDescAr: 'قلب القرآن، وبراهين الرسالة، وقصة أصحاب القرية ومؤمن آل يس، وآيات الشمس والقمر.',
    shortDescEn: 'The Heart of the Quran, vibrant proofs of resurrection, the martyr of the city, and celestial orbits.',
    videos: 125,
    stories: 65,
    images: 180,
  },
  55: {
    meaningEn: 'The Beneficent',
    revelationOrder: 97,
    shortDescAr: 'عروس القرآن، وتكرار «فبأي آلاء ربكما تكذبان»، ووصف جنات النعيم والعيون الجارية.',
    shortDescEn: 'The Beauty of Divine Favors, rhythmic reminders of blessings, and paradise vistas.',
    videos: 130,
    stories: 70,
    images: 195,
  },
  56: {
    meaningEn: 'The Inevitable Event',
    revelationOrder: 46,
    shortDescAr: 'أهوال يوم القيامة، وأقسام الناس الثلاثة: السابقون، وأصحاب اليمين، وأصحاب الشمال.',
    shortDescEn: 'The Inevitable Day, dividing humanity into the Foremost, the Righteous, and the Astray.',
    videos: 85,
    stories: 40,
    images: 110,
  },
  67: {
    meaningEn: 'The Sovereignty',
    revelationOrder: 77,
    shortDescAr: 'المنجية من عذاب القبر، تبارك الملك وخلق الموت والحياة ليبلوكم أيكم أحسن عملاً.',
    shortDescEn: 'The Protector from the Grave, celebrating Divine dominion over life, death, and perfection of deed.',
    videos: 98,
    stories: 52,
    images: 140,
  },
  112: {
    meaningEn: 'Purity of Faith',
    revelationOrder: 22,
    shortDescAr: 'تعدل ثلث القرآن، إخلاص التوحيد وتنزيه الله عن الصاحبة والولد والكفء.',
    shortDescEn: 'Equivalent to one-third of the Quran, declaring absolute monotheism and eternal self-sufficiency.',
    videos: 75,
    stories: 30,
    images: 100,
  },
  113: {
    meaningEn: 'The Daybreak',
    revelationOrder: 20,
    shortDescAr: 'الاستعاذة برب الفلق من شر ما خلق ومن شر غاسق إذا وقب ومن النفاثات والحاسد.',
    shortDescEn: 'Seeking refuge with the Lord of the dawn from darkness, hidden sorcery, and envy.',
    videos: 60,
    stories: 25,
    images: 80,
  },
  114: {
    meaningEn: 'Mankind',
    revelationOrder: 21,
    shortDescAr: 'الاستعاذة برب الناس ملك الناس إله الناس من شر الوسواس الخناس في الصدور.',
    shortDescEn: 'Seeking refuge with the Lord, King, and God of mankind from insidious whisperers.',
    videos: 62,
    stories: 26,
    images: 85,
  },
};

export const ALL_114_SURAHS: SurahExtendedMeta[] = CANONICAL_SURAHS.map((s) => {
  const desc = SURAH_DESCRIPTIONS[s.id] || {
    meaningEn: s.nameEn,
    revelationOrder: s.id,
    shortDescAr: `سورة مباركة من سور القرآن الكريم، تتضمن هدايات ربانية وأحكاماً وإرشادات للمؤمنين.`,
    shortDescEn: `A blessed chapter of the Holy Quran delivering divine guidance, spiritual light, and wisdom.`,
    videos: Math.floor(15 + (s.id * 7) % 40),
    stories: Math.floor(5 + (s.id * 3) % 20),
    images: Math.floor(20 + (s.id * 9) % 60),
  };

  return {
    ...s,
    meaningEn: desc.meaningEn,
    revelationOrder: desc.revelationOrder,
    shortDescAr: desc.shortDescAr,
    shortDescEn: desc.shortDescEn,
    featuredMedia: {
      videos: desc.videos,
      stories: desc.stories,
      images: desc.images,
    },
  };
});
